
spring:
#数据库配置
  datasource:
    name:
    url:
    username: ebs
    password: ebs
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20


mybatis:
  config-location: classpath:mybatis-conf.xml
  mapperLocations: classpath*:mapper/**/*.xml
  type-aliases-package:
  check-config-location: true