spring:
  application:
    name: web-ui

  freemarker:
    request-context-attribute: request
    suffix: .html
    #支持其他jar中的模板文件
    prefer-file-system-access: false

  #国际化配置
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/messages

server:
  port: 81
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
  error:
    path: /main/error

